### ISSUE TITLE
swizzle generate dense tensor instead of sparse

### ISSUE THREAD

**Issue by Paramuths** [finch-tensor/Finch.jl#635]
https://github.com/SparseRooflineBenchmark/SparseRooflineBenchmark/blob/main/src/Generator/spmv.jl
at line 34 and 157, calling copyto!(swizzle(Tensor(Dense(SparseList(Element(0.0)))), 2, 1), A) should generate a Dense of SparseList Tensor. However, the generated matrix is a Dense of Dense.

current fix: Change to swizzle(copyto!(Tensor(Dense(SparseList(Element(0.0)))), permutedims(A)), 2, 1)

**Comment by willow-ahrens** [comment]
Namo, what version of Finch is installed to this environment?

I think this may be fixed, as I cannot reproduce locally.

https://github.com/SparseRooflineBenchmark/SparseRooflineBenchmark/blob/385b02b74cbaf0fb986f69c0a2f2af4e6c7d3d1e/src/Project.toml#L13 says to use a very old finch version, perhaps you could update it?
