### ISSUE TITLE
`Finch.jl`regressions

### ISSUE THREAD

**Issue by hameerabbasi** [finch-tensor/Finch.jl#644]
Failures can be seen starting at: https://github.com/pydata/sparse/actions/runs/11897897564/job/33153177355?pr=809#step:5:12261

The common theme seems to be:

```julia
juliacall.JuliaError: Finch.FinchProtocolError("SparseCOOLevels cannot be updated multiple times")
```

cc @willow-ahrens

**Comment by willow-ahrens** [comment]
fixed in https://github.com/pydata/sparse/pull/812
